name: omnisci-dev
channels:
- conda-forge
- defaults
dependencies:
- thrift=0.13.0
- arrow-cpp=0.15.0
- pyarrow==0.15.0
- pandas>=0.25,<0.26  # ATM cudf uses this pinning
- python>=3.6
- sqlalchemy>=1.3
- numpy>=1.16
- numpydoc
- coverage
- flake8
- pre-commit
- pytest-cov
- pytest-mock
- requests
- shapely
- sphinx
- sphinx_rtd_theme
- rbc=0.2.2
