name: omnisci-gpu-dev
channels:
- conda-forge
- defaults
- nvidia
- rapidsai
dependencies:
- thrift=0.13.0
- cudf=0.13
- cudatoolkit=10.1
- arrow-cpp=0.15.0
- pyarrow==0.15.0
- pandas>=1.0
- python>=3.6
- sqlalchemy>=1.3
- numpy>=1.16
- numpydoc
- coverage
- flake8
- pre-commit
- pytest-cov
- pytest-mock
- shapely
- sphinx
- requests
- sphinx_rtd_theme
- rbc=0.2.2
